# Generated by Django 5.1.6 on 2025-02-26 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('reg_number', models.IntegerField()),
                ('gender', models.IntegerField(choices=[(1, 'Самец'), (2, 'Самка')])),
                ('breed', models.IntegerField(choices=[(1, 'Собака, беспородная'), (2, 'Кошка, беспородная')])),
                ('municipality', models.IntegerField(choices=[(1, 'г. Мурманск'), (2, 'г. Апатиты'), (3, 'г. Мончегорск')])),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.IntegerField(choices=[(1, 'Отлов'), (2, 'Первичный осмотр'), (4, 'Клинический осмотр'), (12, 'Содержание'), (9, 'Возврат в прежнюю среду')])),
                ('execution_date', models.DateTimeField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='Animal.animal')),
            ],
        ),
    ]
